### ISSUE TITLE
Density for Clouds

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#121]
### Description

Currently, the density of clouds is hard coded. That makes it impossible to adjust the effect to only have very few or very many clouds.

The cloud weather effects should allow configuring the density, adjusting the maximum number of particles, frequency, and lifetime as needed, so that the effect looks sensible in all possible slider positions. It should allow configuring a very lightly clouded effect as well as a very heavily clouded effect, that almost covers everything.

### Context

Feature request from discord: https://discord.com/channels/749312958823268352/749320643060957326/922990615921324082

**Comment by yjeroen** [comment]
I'd love this feature as well!

Including maybe opacity setting.
