### ISSUE TITLE
Weather mask breaks if a masking drawing isn't completely contained in the scene rectangle

### ISSUE THREAD

**Issue by dev7355608** [ghost-fvtt/fxmaster#124]
Relevant code:
https://github.com/ghost-fvtt/fxmaster/blob/aa41c67addcd79211d049c9a76b6c4245e08f6e3/src/module/weatherEffects/WeatherLayer.js#L60

The issue is that `beginHole/endHole` only works if the hole shape is completely contained in the shape that is holed. So it has to be `const sceneShape = canvas.dimensions.rect;`; otherwise we get unexpected behavior if a masking drawing is partially in the padded region.

I suggest to add a separate mask to the weather layer that just restricts weather to the scene rectangle if there's no background image.

Particle system region should be restricted to the scene rectangle as well. That should increase the performance considerable, I assume. The default padding is 25%, so the padded region makes up 36% percent of the canvas, in which particles are simulated that are hidden anyway.

**Comment by ghost91-** [comment]
After having fought a bit with with how the mask mask for the layer is being destroyed, I think I figured it out now (and actually was able to simplify some more code doing stuff more similar to what core does...).

However, I don't really have an idea yet how to limit the particle region. I'm not even sure if I understand correctly what you mean by that. From my understanding, there is no region for the particles, they are simply spawned into the given container (which in this case is `canvas.fxmaster.weather`) according to their spawn behavior (most of the effects simply use a spawn rectangle). The spawn areas are already chosen in a way that make sense, with respect to the scene dimensions, e.g. autumn leaves will only spawn inside the scene rect (but they can move outside of it). And then they just life as long as their lifetime dictates. I didn't see any way to inherently limit the area in which the particles can be, or "despawn" them if they leave a certain area. So am I missing anything here? Or did I understand you incorrectly?

**Comment by dev7355608** [comment]
I actually don't how to limit the region. I'd have to look into it. I just saw the rain effect covering the entire canvas and thought it seemed unnecessary.

**Comment by ghost91-** [comment]
Some effects intentionally start outside of the visibility area so that it looks like The particles move into the area and don’t just spawn in it. I think rain is one of those. But  I can take a closer look again to see if the spawn area is as optimal as possible.

**Comment by ghost91-** [comment]
Closed by #125

Regarding avoiding drawing particles outside of the scene. The current way is accepted for now. Performance improvements might be considered later.
