### ISSUE TITLE
Compatibility issue with Perfect Vision in Foundry V9 

### ISSUE THREAD

**Issue by zacdemon** [ghost-fvtt/fxmaster#128]
### Expected Behavior

Scenes should load without issue

### Current Behavior

When perfect vision and FX master are active new scenes will not load.

### Steps to Reproduce

1. Activate the Perfect Vision and FX Master modules along with any dependencies in the DnD 5e system
2. Attempt to load into a new scene
3. Scene will fail to load

### Version

v2.0.0

### Foundry VTT Version

V9.238

### Operating System

Server: Linux (Ubuntu) User: Windows

### Browser / App

Microsoft Edge

### Game System

dnd5e

### Relevant Modules

Perfect Vision

**Comment by ghost91-** [comment]
Which version of Perfect Vision are you using?

**Comment by zacdemon** [comment]
Version is 3.2.2

**Comment by ghost91-** [comment]
Ok, we tested it with 3.1.0 and 3.1.1, maybe something broke again in a newer version. Do you see any errors when you open the dev console (F12)?

**Comment by zacdemon** [comment]
> Ok, we tested it with 3.1.0 and 3.1.1, maybe something broke again in a newer version. Do you see any errors when you open the dev console (F12)?

[Error.log](https://github.com/ghost-fvtt/fxmaster/files/7775125/Error.log)
Attached is the error log from the console.

**Comment by dev7355608** [comment]
PV's fault. Fixed in 3.2.3.
