### ISSUE TITLE
Disabling in module settings have no function

### ISSUE THREAD

**Issue by Grizzly90** [ghost-fvtt/fxmaster#139]
### Expected Behavior

Disabling FXMaster effects like crows if the checkbox "Enable FXMaster" is unchecked and/or "Disable Effects for everybody" is checked. 

### Current Behavior

Checkboxes doesn't seems to have any effect on crows and birds (even after reload with F5)

### Steps to Reproduce

* Electron or Nodjs Version of Foundry: Version 9 - Build 238
* FXMaster V2.0.2
* Chrome on Windows10
* Any scene with activated crows and birds
* 

### Context

I did a rollback to V2.0.0 because I remeberd that it used to work on my Fondry V9 setup and on 2.0.0 the "Disable Effects for everybody" works as expected, while "Enable FXMaster" still doesn't change anything. 

after updating again with "Disable Effects for everybody" checked the crows still don't fly. But after unchecking, reload and checking again the crows won't disappear.

### Version

v2.0.2

### Foundry VTT Version

Version 9 - Build 238

### Operating System

Win10

### Browser / App

Chrome

### Game System

DSA5

### Relevant Modules

FXMaster and "The Dark Eye - Introduction Adventure"

**Comment by ghost91-** [comment]
Thanks for the report, this is fixed in v2.1.0.
