### ISSUE TITLE
Weather effects not working within area of light sources

### ISSUE THREAD

**Issue by Aezrel** [ghost-fvtt/fxmaster#149]
### Expected Behavior

Weather effects such as clouds/embers/fog are not affected by lighting

### Current Behavior

In the light source's area of effect, weather effects disappear. They continue moving across the map (you can see an effect entering the area of the light source, disappear and then come out the other side) but don't show up within the area of the light.

### Steps to Reproduce

1. Add lightsources to map
2. Add weather effects

### Context

![Screenshot_1](https://user-images.githubusercontent.com/97117980/148096024-31eca9fa-5ef7-46ce-91d9-f3f470252595.png)

### Version

2.1.1

### Foundry VTT Version

9.238

### Operating System

Windows 10

### Browser / App

Chrome

### Game System

dnd5e

### Relevant Modules

Sequencer, weatherblocker, dynamic illumination, lessfog

**Comment by ghost91-** [comment]
Thanks for the report. I was not able to reproduce this locally, it seems to be working just fine:
![20220104_20h14m14s_grim](https://user-images.githubusercontent.com/236845/148111674-8762f646-5b9d-479e-a85c-0c231577eb10.png)

I tried this with all the modules you listed activated. Are you using any other modules? What lighting settings are you using? Could you export the problematic scene and send it to me, so I can try it with that?

**Comment by Aezrel** [comment]
HI, thanks for picking this up! Here's my full module list and the scene, as well as a screenshot of the lighting settings:

Active Modules:
----------
5e-Sheet Resources Plus v1.6.11;
Actor Attribute Lists v0.0.5;
Actually Private Rolls v0.2;
Advanced Macros v1.13;
Automated Animations v1.1.0;
Backgroundless Pins v1.2.03;
Better Rolls for 5e v1.7.1;
Combat Utility Belt v1.8.0;
DFreds Droppables v1.4.0;
Dice So Nice! v4.3.0;
Dice So Nice - Weighted Companion Cube Dice Set v1.0.2;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.76;
Dynamic Illumination v0.9.0;
Entice with Dice so Nice v0.0.16;
Forgotten Adventures Extensive DM Screen v0.4.2;
Forien's Quest Log v0.7.9;
Forien's Unidentified Items v0.4.0;
FXMaster v2.1.1;
GM Notes v0.5.0;
Health Estimate v26.12;
Image Previewer v0.7;
Initiative Double Click v1.2;
Jack Kerouac's Animated Spell Effects v0.6.8;
JB2A - Patreon Complete Collection v0.3.4;
Less Fog v0.9.0;
lib - Color Settings v2.8.1;
Library: DF Hotkeys v2.3.5;
libWrapper v1.11.1.0;
Loot Sheet NPC 5e v3.4.1;
Lordu's Custom Dice for Dice So Nice v0.33;
Monk's Scene Navigation v1.0.21;
Multilevel Tokens v1.5.2;
Nice More Dice v1.0.3;
Permission Viewer v0.9.1;
Pin Cushion v1.5.0;
Pings v1.3.0;
Polyglot v1.7.28;
Sequencer v1.3.5;
Settings Extender v1.2.0;
Show Notes v0.5;
Simple Calendar vv1.3.75;
Smart Target v0.8.4;
socketlib v1.0.10;
Soundscape v1.0.3;
Split Journal v1.1;
The Furnace v2.6.1;
Tidy5e Sheet v0.5.21;
Tidy UI - Game Settings v0.1.28;
Token Attacher v4.3.1;
Token Auras v1.15;
Token Health v0.5.1;
Token HUD Wildcard v1.5.0;
Token Magic FX v0.5.2.3;
Weather Blocker v0.7;
Weather Control v4.1.3;

Inactive Modules:
----------
Adventure Importer / Exporter v0.7.1;
Adventure Music v1.1.0;
Magic Items Vol.10 - Victorian Horror v2.0.2;
Magic Items Vol.11 - Antimagic Corruption v2.0.1;
Magic Items Vol.12 - Cakewalk v2.0.1;
Magic Items Vol.13 - High Seas Horror v2.0.2;
Magic Items Vol.15 - Mad Biomancer v2.0.1;
Magic Items Vol.16 - Touch of Fey v2.0.1;
Magic Items Vol.17 - Eastern Relics v2.0.1;
Magic Items Vol.18 - Nine Hells v2.0.2;
Magic Items Vol.19 - Astral Adventures v2.0.2;
Magic Items Vol.21 - The Celestial Treasury v2.0.1;
Magic Items Vol.2 - Sunken King v2.0.1;
Magic Items Vol.3 - Cultists v2.0.2;
Magic Items Vol.4 - Frozen Norse v2.0.2;
Magic Items Vol.6 - Magitech Mayhem v2.0.2;
Magic Items Vol.7 - Welcome to the Jungle v2.0.2;
Magic Items Vol.9 - Body Augmentation v2.0.1;
Maxwell's Manual of Malicious Maladies v0.9.8.2;
Michael Ghelfi Studios Audio Pack v1.3;
SoundFx Library v1.0.1
[fvtt-Scene-the-caldera.txt](https://github.com/ghost-fvtt/fxmaster/files/7817337/fvtt-Scene-the-caldera.txt)
![Screenshot_4](https://user-images.githubusercontent.com/97117980/148277758-5f5461e4-de5d-47e3-9c26-83e41f069bae.png)
;

**Comment by ghost91-** [comment]
Thanks for the detailed list and the exported scene! Let's see if I can reproduce it with that :)

**Comment by zstix** [comment]
I'm also running into this issue (notice the embers in the dark parts of the windmill interior - which isn't lit):
![Screen Shot 2022-01-05 at 11 48 17](https://user-images.githubusercontent.com/1946433/148279714-ddd3564e-28ba-4f12-a939-d92c60175517.png)

I'd _really_ like to add some rain / fog to this scene but, because I have the outside illuminated with lights, I'm unable to produce that effect. Let me know if there's anything I can do to help (happy to help dig into the code / console).

**Comment by ghost91-** [comment]
>  Let me know if there's anything I can do to help (happy to help dig into the code / console).
You could try deactivating all other modules and see if the issue persists. If it doesn't, you could use the find the culprit module to figure out which of the modules causes the conflict.

**Comment by zstix** [comment]
@ghost91- I just went through and disabled each module individually (list below - I don't use too many) and was unable to get this working right. I then disabled _all_ of the modules except FXMaster and I am still seeing this issue. Just double-checked and I am on the latest version of the module.

* Bellows
* Chat Portrait
* D&D Beyond Importer
* Dice So Nice!
* Dice Tray
* FXMaster
* Loot Sheet NPC 5e
* Multilevel Tokens
* Pings
* Settings Extender
* Torch

**Comment by ghost91-** [comment]
@Aezrel some of those modules break your scene even without FXMaster. I would strongly recommend you to rethink some of the module choices. Most of them are not marked ready for V9. Some even haven't been updated since foundry 0.5... It's difficult to test it this way. With all the modules deactivated (except for FXMaster), things look fine on my end (the warning triangles are due to the missing assets):

![20220105_21h17m04s_grim](https://user-images.githubusercontent.com/236845/148283296-02e1ba57-d9fd-4848-bf1d-608bf0a5aed0.png)

**Comment by ghost91-** [comment]
@zstix Could you export your scene, and upload it as a zip, with all the required assets (background image, any tiles that are being used, etc.)?

**Comment by ghost91-** [comment]
@Aezrel ok, after activating the modules one by one, it's now also working with all those modules on my side. I don't see what you are seeing...
![20220105_21h22m28s_grim](https://user-images.githubusercontent.com/236845/148283893-0d65cf09-b534-4e5b-a380-eb3df48bbb92.png)

**Comment by ghost91-** [comment]
could you try and see what happens with regular weather effects from foundry core? I.e., deactivate FXMaster and set a weather effect in the Ambience tab of the scene configuration, e.g. the autumn leaves. DO those leaves appear in the light areas?

**Comment by ghost91-** [comment]
Also, could you try a different browser? If you've been using Chrome, try Firefox, etc.

This all seems really weird to me... oO

**Comment by zstix** [comment]
Trying in firefox, I got the following error:

```
Uncaught (in promise) InternalError: too much recursion
    get foundry.js:2122
    draw WeatherLayer.js:153
```

Here's a JSON export of the scene I'm working with. I haven't exported a scene before, so let me know if you need anything else:
[fvtt-Scene-the-windmill.json.zip](https://github.com/ghost-fvtt/fxmaster/files/7817629/fvtt-Scene-the-windmill.json.zip)

**Comment by ghost91-** [comment]
That's also a weird error.... I'll have to look into that, too. With your scene, I am able to reproduce it now. And I figured out, what exactly causes it: If you change some of the settings in the Advanced Options of a light source, such as Luminosity, or Background Saturation, the particles vanish... I'll have to look deeper into how the new lighting system works in order to figure out how to avoid that...

**Comment by ghost91-** [comment]
The core weather effects avoid this problem by simply putting the weather effect layer above the lighting layer. Doing the same for FXMaster "fixes" the issue but then weather effects are not affected by lighting / sight anymore. In particular, effects are visible in black fog of war areas. It's the same for the core weather effects but this really sucks...

**Comment by ghost91-** [comment]
Looks like putting it into the primary group also works...

**Comment by ghost91-** [comment]
I just created a new release That should fix the problem. Could you check if it works correctly now, @Aezrel and @zstix? Would also be cool if you could check for that error in firefox, again, @zstix. I made a small adjustment that hopefully fixes that problem.

**Comment by zstix** [comment]
@ghost91- Yaaas it's fixed!

![Screen Shot 2022-01-05 at 14 52 25](https://user-images.githubusercontent.com/1946433/148301245-48654371-1230-45e6-8acc-cfd01726042a.png)

I'm also no longer seeing that error in Firefox. Thank you so much for the quick turnaround time! I really appreciate it!

**Comment by Aezrel** [comment]
@ghost91- @zstix Wow, you guys were hard at work! I updated the module to the latest version and it's fixed for me too!

I know my mod list is a controversial topic but weirdly enough it's been working fine, actually xD; sorry it was extra work for you though, glad zstix was able to help. Thanks for the fix and for all your hard work!
