### ISSUE TITLE
Allow the playVideo() function to set which layer it plays on

### ISSUE THREAD

**Issue by crnormand** [ghost-fvtt/fxmaster#170]
### Description

Currently, all videos played using the `canvas.specials.playVideo(videoData)` function all seem to play above the Actor layer. 

This works great for most things and we have incorporated it into our game system through a chat command `/anim` (https://www.youtube.com/watch?v=BAyko-unrEQ.

However, there are some instances (like rolling fog, portal animations, etc.) that would look better under the actor token.  Would it be possible to add an attribute the videoData object to set which layer we want the animation to play on?

### Context

I wasn't certain if this was a duplicate of https://github.com/ghost-fvtt/fxmaster/issues/61.

**Comment by ghost91-** [comment]
Hi @crnormand, thanks for the suggestion! 

This is certainly possible and probably not even that difficult. However, I don’t really plan to work FXMaster's webm special effects functionality at this point anymore.

The reason for this is that by now, the sequencer module provides almost all of the functionality regarding webm special effects that FXMaster provides, but in a better way and with a lot more features. For example, sequencer already provides the functionality you asked for here (effects in front of and behind tokens). So it just makes much more sense for FXMaster to focus on weather effects and filters and let sequencer deal with webm special effects.

I am even considering to remove that part of FXMaster at some point. Of course, I first need to find out who depends on this functionality, so it’s good to know that you are using it in your system. I won’t just remove it if you still need it. But I think in most cases, switching to sequencer for webm effects is the better choice and I would recommend you to consider doing that.
