### ISSUE TITLE
Module stop working

### ISSUE THREAD

**Issue by Ychabod** [ghost-fvtt/fxmaster#192]
### Expected Behavior

Working ! :)

### Current Behavior

The icon of Fxmaster stop showing, and the weather disapared on the map, even the module was activated

### Steps to Reproduce

arf.. don't know really

### Context

It's not the first time I have this problem..
it disapared when I upgrade foundry, and I discovered that the icon reappared when I deleted the folder on my appadata/roaming/foundry
Maybe a cache problem ? Or an option in foundry ?

### Version

V2.2.2

### Foundry VTT Version

V9.245

### Operating System

W10

### Browser / App

Firefox

### Game System

Simple world building

### Relevant Modules

with only fxmaster on a campaign it's happening

**Comment by ghost91-** [comment]
Do you see any errors in the dev console (F12)?

**Comment by Ychabod** [comment]
Nope, no errors

**Comment by ghost91-** [comment]
OK, that’s weird. Did you scroll all the way back up in the console?

**Comment by ghost91-** [comment]
If there is no error at all and you are sure that FXMaster is actually activated, but it still doesn’t work, I'm not sure how I can help with that. You could check in the network tab of the dev tools, if FXMaster is actually being loaded (check for a file called `fxmaster.js` and a file `pixi-filters.js`.

**Comment by SkyRushSoul** [comment]
I've had a similar issue. I did find the error however.

Failed to load module script: modules/fxmaster/css/common.css:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by ghost91-** [comment]
@SkyRushSoul I think I have seen that before and it was related to caching. Please try pressing CTRL + F5 and see if that fixes it. If it doesn’t, please try uninstalling and reinstalling FXMaster.

**Comment by SkyRushSoul** [comment]
> @SkyRushSoul I think I have seen that before and it was related to caching. Please try pressing CTRL + F5 and see if that fixes it. If it doesn’t, please try uninstalling and reinstalling FXMaster.

The refresh didn't work, but the reinstallation did. I apologize. Thought I had tried that already earlier today. Thanks for the advice.

**Comment by Ychabod** [comment]
For me, reinstalling isn't resolving the problem.
For now it worked, I have deleted my appdata folder
If it shows again, I will tell you :)

**Comment by ghost91-** [comment]
OK, it seems like an issue that’s related to your setup then, @Ychabod. Not sure if I can do anything about it if it happens again. Closing this as it seems to be resolved for now.

**Comment by Ychabod** [comment]
Same issue came back..
No error on console, it loads pixi.js fine

Before doing anything:
![Capture](https://user-images.githubusercontent.com/97633425/152652540-7ff8b0b3-1934-435a-9c15-e4828fc12a51.PNG)

This time, I've tried to delete the appdata/roaming/cache folders one by one.
It does nothing, so I've uninstal it. When I've reinstall it, foundry closed himself... and Tada ! it re-appeared
