### ISSUE TITLE
Mask Weather in conjunciton with Levels Module

### ISSUE THREAD

**Issue by Jamo181** [ghost-fvtt/fxmaster#221]
### Description

I may just be missing something but is there a way of enabling the weather to be masked by the level module settings if present?
![image](https://user-images.githubusercontent.com/43423302/156865748-104ace9b-c574-441d-8194-f5b12cdf9c04.png)
This would allow weather effects to be blocked whilst the token is inside the building but when looking at the roof it's still shown?

**Comment by ghost91-** [comment]
To be honest, I have no clue about the Levels module. I don’t even know what exactly you are asking for here. I have no plans to add integration with other modules on the side of FXMaster. If you want FXMaster and Levels to integrate, you will have to ask theripper93 to add integration on the Levels side. I know he has added integration with FXMaster for his weather blocker module, so maybe he is willing to do that.

so for now, there are just 2 options for masking weather:
- use the weather masking functionality of FXMaster
- use theripper93's Weather Blocker module
