### ISSUE TITLE
Compatibility with V10

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#234]
### Description

Support for Foundry VTT v10 should be added. v10 switched from `pixi-particles` to `@pixi/particle-emitter`, which has quite a few breaking changes. All of the configuration of weather effects should be updated to match the new format. It is quite likely that it is not possible to keep backwards compatibility for v9, so it should simply be dropped.

This also presents itself as an opportunity to perform some refactoring and cleanup.

**Comment by DrMcCoy** [comment]
A minor thing, but support for "entity"-only packs lists in module.json will be removed with Foundry VTT V10: https://gitlab.com/foundrynet/foundryvtt/-/issues/6666.

**Comment by ghost91-** [comment]
I am aware of that, but thanks for the hint :)
