### ISSUE TITLE
FEATURE REQUEST: Let us pick which feature effect applies to what layer, instead of all of them applying to the same ones

### ISSUE THREAD

**Issue by GambetTV** [ghost-fvtt/fxmaster#244]
### Description

Sometimes I want to use different effects on different objects. Say, I might want to apply a Color Filter to the whole map, including tokens and roofs, but I might want to apply the Underwater filter only to the map, not including drawn objects or rooftops or tokens. Currently all filters apply to the same things, so if I want the Color Filter to affect maps and tokens, then my Underwater filter must also do so. Would be great if every entry could have their own settings.

**Comment by ghost91-** [comment]
Thanks for the report. I am considering something similar to this as a solution for #103. the idea would be that the layer selection happens for each effect individually, and for filter effects where it doesn’t work correctly (such as bloom), the options simply wouldn’t be available.

**Comment by ghost91-** [comment]
Unfortunately, in v10 it won’t be possible to apply filter effects to different layers anymore at all, due to limitations in foundry core. So I’m closing this as a wontfix.
