### ISSUE TITLE
Add Opacity Slider to Particle Effects

### ISSUE THREAD

**Issue by Tmktahu** [ghost-fvtt/fxmaster#305]
### Description

I suggest adding the ability to change the opacity/transparency of a given weather effect. This would be specifically useful for things like simulating cloud shadows with the clouds effect, reducing how noticable rain effects can be, or having better control over how opaque the fog effect is.

**Comment by ghost91-** [comment]
No news yet. It's not very difficult to implement, I just need to find the time to do it. PRs are welcome, if anybody wants to help :)

**Comment by jacksands** [comment]
Sorry but I have zero knowledge in programming, I'm a photographer... kkkk
In any case if there something that I can do just say it.

And thank you for your effort and time!!

**Comment by ghost91-** [comment]
No worries, I'm glad you like it :)
