### ISSUE TITLE
[bug] Per-scene weather effects are offset when changing between scenes of different aspect ratios

### ISSUE THREAD

**Issue by magroader** [ghost-fvtt/fxmaster#383]
### Expected Behavior

If I have multiple scenes with weather effects and different aspect ratios, and I switch between them, the weather effects should look correct.

### Current Behavior

When switching between scenes with weather effects and different aspect ratios, one of the scenes' weather effects may end up offset such that the top/left area of the screen is not covered by the effect.

### Steps to Reproduce

1. Have an empty world with no mods enabled
2. Create 2 scenes with differently-sized backgrounds, say one a smaller square and another a 1280x720 image. For each, in the Ambience tab, turn on Rain. Also, make each Gridless (Grid tab), and turn off Token Vision and Fog Exploration (Lighting) (not sure if these last bits are necessary, but I'm being thorough).
3. Toggle back and forth between these scenes, notice everything is fine <img width="198" alt="image" src="https://user-images.githubusercontent.com/151634/201427393-2f65d701-49cd-4831-822a-cbb4cb8b9541.png">
4. Turn on FXMaster
5. Toggle back and forth between these scenes. When going to one of them (for me, the smaller square image), the rain effect will be missing from the left and/or top area <img width="274" alt="image" src="https://user-images.githubusercontent.com/151634/201427326-018f2e8c-af29-4807-8ece-b6d6b1afa5cb.png">

### Context

No errors in the console!

Make sure to toggle back and forth between scenes - it can look correct the first time it's loaded, but then when toggling back and forth it breaks.

### Version

3.5.0

### Foundry VTT Version

10.290

### Operating System

Windows

### Browser / App

Native Electron App, Chrome

### Game System

dnd5e

**Comment by ghost91-** [comment]
Fixed in cd875dc
