### ISSUE TITLE
Rectangles of FX missing/masked after scene changes.

### ISSUE THREAD

**Issue by darloth** [ghost-fvtt/fxmaster#393]
### Expected Behavior

I have no masks enabled for a given scene, so I expect a particle fx to cover the entire scene.

### Current Behavior

I get weird rectangles cut out of the scene, like so:
![screenshot](https://user-images.githubusercontent.com/8480048/205305627-84443834-2865-4f8f-9532-f173ba4426dd.jpg)

### Steps to Reproduce

1. Set obviously visible weather going for some scene - fog, rain, clouds together seems good.
2. Switch to a different scene
3. Switch back to that original scene and observe big blank rectangles with no weather across it.

### Context

If I turn off FxMaster, and just use a foundry default rain ambiance, it covers the entire scene.  If I turn on FxMaster then the default rain is masked in those areas, leading me to suspect that FxMaster's masking is the culprit here.

If I restart FxMaster (disable module, reload, enable module, reload) then the scene displays correctly on first load.
If I switch between scenes (even those with no masks enabled) then the problem comes back.

I have masks enabled on another scene, and I didn't experience this problem until I masked up that scene.  That scene has invert masks turned on.  The scenes with the problem do not, but if I DO toggle invert masks for the scenes with the problem, they still have the problem and invert masks works as expected (it masks away ALL the effects, then they come back inside a drawing, but still have the same areas missing that they did before I toggled the masking, even inside the drawing).  Even if I turn invert masks off for that scene the problem still occurs.  Could also be due to some scenes having resized base images maybe?

Each new scene switched to after a fresh load causes new 'masked' rectangles to draw on the original problem scene, even when the new scenes have no drawings involved.

I've reproduced this behaviour with no other modules active except FxMaster.

### Version

v3.5.0

### Foundry VTT Version

v10.290

### Operating System

Linux Ubuntu Focal Fossa, but players on Windows also saw it.

### Browser / App

Native Electron App, Chrome, Firefox

### Game System

PF2e v4.4.0

**Comment by darloth** [comment]
Damnit this is fixed in 3.5.1 which I only noticed existed when I made this report.

Oh well, at least you've got confirmation the fix worked.  I swear I searched around to try and find an issue for it.  Sorry for the duplicate report, though I still can't find the original one!

**Comment by ghost91-** [comment]
It’s probably this: https://github.com/ghost-fvtt/fxmaster/issues/383

the description may be a bit different, but it’s the same underlying issue.

no worries though, glad you found the update now :)
