### ISSUE TITLE
Effects not visible with Hardware acceleration enabled

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#59]
In GitLab by @Naitbit on Jun 3, 2021, 14:26
https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/-/issues/107

Neither weather effects nor filters are visible when using the browser with Hardware acceleration enabled.
They are visible as expected on browser that uses software only rendering.

tested on:
Foundry VTT 0.8.6
FXMaster 1.0.9

Two Linux machines (one with Nvidia graphics card another one with AMD) with Firefox and Chromium webbrowser. Also mentioned by some users on Discord fe: https://discord.com/channels/170995199584108546/722566083499786352/846603787811684382

![grafik](https://user-images.githubusercontent.com/236845/145695595-41360c70-abe3-47ff-921a-0ea607737722.png)
(Left Chromium with Hardware acceleration enabled, Right FF with hardware acceleration disabled)

**Comment by ghost91-** [comment]
In GitLab by @mesfoliesludiques on Jun 9, 2021, 15:25

Hi ! No vision at all from what I see ? I don't think I can do much !

**Comment by ghost91-** [comment]
Hi @Naitbit, is this still happening to you with the most recent version? I am having trouble reproducing this.

**Comment by Naitbit** [comment]
It works for me now. So issue is likely obsolete. 

Retested on:
Foundry VTT 0.8.9
FXMaster 1.2.1

**Comment by ghost91-** [comment]
Thanks for the feedback, closing this then :)
