### ISSUE TITLE
Particle Effects doesn't work

### ISSUE THREAD

**Issue by Ksenichiro** [ghost-fvtt/fxmaster#600]
### Expected Behavior

Particle Effects must appear after saving changes in Particle Effects Manager
![image](https://github.com/ghost-fvtt/fxmaster/assets/47676089/ccf01817-5638-41e8-b73e-0764e671bc8a)

### Current Behavior

After saving settings of particle effects I get nothing and the "save changes" button turns off grey and inactive. I get nothing in the console after saving changes. Still can apply weather effects by changing scene preferences. 

### Steps to Reproduce

Change settings in Particle Effects Manager.
try to save it

### Version

4.0.2

### Foundry VTT Version

11.305

### Operating System

Windows 11

### Browser / App

Chrome

### Game System

dnd5e 2.3.1

**Comment by ghost91-** [comment]
Please check the FXMaster settings to see if effects are disabled there.

**Comment by Ksenichiro** [comment]
> Please check the FXMaster settings to see if effects are disabled there.

I feel a little bit stupid now, thanks for your help :D
