### ISSUE TITLE
FXMaster does not work anymore

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#73]
In GitLab by @kvnsvg12 on Jul 3, 2021, 19:31
https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/-/issues/143

Getting errors and the weather does not function.

**Comment by ghost91-** [comment]
In GitLab by @modzy2 on Jul 4, 2021, 08:51

Density doesn't seem to scale for larger maps.  If I set a tiny map, say 400x300 pixels, and turn on snow, it looks good.  As the map gets larger, the density value doesn't seem right, but if I override it with ever larger values, the visible density only gets to a certain level, and further increases to the value in the setting don't seem to have any further effect.

**Comment by ghost91-** [comment]
In GitLab by @mesfoliesludiques on Jul 4, 2021, 11:15

Can you give details and screenshot @kvnsvg12 ?

**Comment by ghost91-** [comment]
In GitLab by @irbian on Jul 5, 2021, 24:25

Don´t know if this is the same error

fvtt: 0.8.8
```
WeatherLayer.js:160 Uncaught (in promise) TypeError: Cannot read property 'callback' of undefined
    at WeatherLayer.js:160
    at Array.forEach (<anonymous>)
    at WeatherLayer.configureEffect (WeatherLayer.js:158)
    at WeatherLayer.drawWeather (WeatherLayer.js:150)
    at fxmaster.js:84
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at Canvas.draw (foundry.js:17520)
    at async Scene.view (foundry.js:15481)
    at async Game.initializeCanvas (foundry.js:4418)
``

**Comment by ghost91-** [comment]
In GitLab by @dionaga on Jul 6, 2021, 24:05

I get this error when regenerating weather using Calendar/Weather. Not sure if it's a you problem or a them problem, but I'll post it for both of you just in case. 

```
WeatherLayer.js:160 Uncaught (in promise) TypeError: Cannot read property 'callback' of undefined
    at WeatherLayer.js:160
    at Array.forEach (<anonymous>)
    at WeatherLayer.configureEffect (WeatherLayer.js:158)
    at WeatherLayer.drawWeather (WeatherLayer.js:150)
    at fxmaster.js:94
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8880)
    at foundry.js:8819
    at Array.map (<anonymous>)
(anonymous)	@	WeatherLayer.js:160
configureEffect	@	WeatherLayer.js:158
drawWeather	@	WeatherLayer.js:150
(anonymous)	@	fxmaster.js:94
_call	@	VM882:4
callAll	@	foundry.js:153
callback	@	foundry.js:8880
(anonymous)	@	foundry.js:8819
_handleUpdateDocuments	@	foundry.js:8819
_updateDocuments	@	foundry.js:8707
async function (async)		
_updateDocuments	@	foundry.js:8698
update	@	backend.mjs:154
async function (async)		
update	@	backend.mjs:151
updateDocuments	@	document.mjs:366
update	@	document.mjs:448
setFlag	@	document.mjs:596
resetFlags	@	utils.js:8
(anonymous)	@	hooks.js:41
_call	@	VM882:4
call	@	foundry.js:179
genPrecip	@	weatherTracker.mjs:635
generate	@	weatherTracker.mjs:695
(anonymous)	@	calendar.mjs:555
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2
```

**Comment by ghost91-** [comment]
In GitLab by @nserluco on Jul 10, 2021, 22:14

I'm getting the same error as the others in this thread. If I go to Weather Controls from the sidebar, I can see that Calendar/Weather is setting the weather correctly though no weather effects are being displayed. If I regenerate the weather from Calendar/Weather, I get a flash of the weather effect that should have been showing and then all effects disappear. Also, if I try force a weather effect to show up from the sidebar, I can't turn it off. Even though I turn it off through the sidebar, the effect still shows until I refresh Foundry.

```
WeatherLayer.js:160 Uncaught (in promise) TypeError: Cannot read property 'callback' of undefined
    at WeatherLayer.js:160
    at Array.forEach (<anonymous>)
    at WeatherLayer.configureEffect (WeatherLayer.js:158)
    at WeatherLayer.drawWeather (WeatherLayer.js:150)
    at fxmaster.js:94
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8880)
    at foundry.js:8819
    at Array.map (<anonymous>)
```

**Comment by ghost91-** [comment]
The issue regarding `Cannot read property 'callback' of undefined` is the same as #91, see https://github.com/ghost-fvtt/fxmaster/issues/91#issuecomment-991818457 and the updated readme for a solution.

@modzy2, @irbian does the issue still persist?

**Comment by ghost91-** [comment]
Closing due to lack of feedback and not being able to reproduce it.

**Comment by irbian** [comment]
I´m using last versions of everything and don´t see errors (fvtt 9.241 fxmaster 2.1.2)
