### ISSUE TITLE
Manifest warning

### ISSUE THREAD

**Issue by ddbrown30** [ghost-fvtt/fxmaster#730]
### Expected Behavior

The "FXMaster" module's manifest contained the following unknown keys: "manifestPlusVersion"

### Current Behavior

The "FXMaster" module's manifest contained the following unknown keys: "manifestPlusVersion"

### Steps to Reproduce

1

### Version

4.0.2

### Foundry VTT Version

v12.328

### Operating System

Windows

### Browser / App

Firefox

### Game System

aaa

**Comment by ghost91-** [comment]
fixed in #765
