### ISSUE TITLE
Clouds keep disappearing

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#83]
In GitLab by @cs96and on Jul 15, 2021, 18:43
https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/-/issues/156

Foundry: v0.8.8

FX Master: v1.2.1

Sometimes all the clouds will suddenly just vanish off the scene.  There are no errors in the console when this happens.  The only way to get them back is to go back into the FX Master settings, fiddle with a setting and then save.

**Comment by ghost91-** [comment]
In GitLab by @cs96and on Jul 15, 2021, 18:43

changed the description

**Comment by ghost91-** [comment]
In GitLab by @Uniwars68 on Jul 18, 2021, 16:43

I get the same issue, with fog too

also I get an error when loading in :
![image](/uploads/3a2eb4b062f1b821bd1c81df9fedabc9/image.png)

**Comment by ghost91-** [comment]
In GitLab by @SirGawain on Jul 24, 2021, 17:52

Same issue (with fog) here, getting exactly the same error in console.

**Comment by ghost91-** [comment]
In GitLab by @ravingdragoon on Jul 27, 2021, 18:38

I am getting this with Clouds and Embers as well. With the same error (expanded) attached.[WeatherLayerError.txt](/uploads/c8c41474710763db639faad2036706f7/WeatherLayerError.txt)

*Edit:* The error occurs when changing scenes to a scene with any effect from any other scene, regardless of if weather is enabled in that other scene. Once this has happened, the error will occur every time you load the scene with the effect, until the weather controls are manually reset. So basically you have to set your weather effects right as you are entering the scene with your players, unless it is your starting scene or your only scene.

**Comment by ghost91-** [comment]
In GitLab by @BlackMoons on Aug 30, 2021, 04:34

Having this issue with fog, though I get a different error.

`The specified value "undefined" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.` about 10~20 times when it occures. 

With a stack trace of:
xe	@	jquery.min.js:2
S.parseHTML	@	jquery.min.js:2
S.fn.init	@	jquery.min.js:2
S	@	jquery.min.js:2
_renderInner	@	foundry.js:2222
async function (async)		
_renderInner	@	foundry.js:2220
_renderInner	@	foundry.js:2747
_render	@	foundry.js:2055
async function (async)		
_render	@	foundry.js:2049
🎁call_wrapped	@	libWrapper-wrapper.js:467
🎁Application.prototype._render#lib-wrapper	@	listeners.js:118
🎁Application.prototype._render#0	@	libWrapper-wrapper.js:162
_render	@	foundry.js:2736
render	@	foundry.js:2011
onClick	@	controls.js:29
_onClickTool	@	foundry.js:27752
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2



It appears setting the density value very low can avoid this error, otherwise it seems to occure very quickly when density is set to 400 on a medium sized map (4760x3080 pixels, 140 grid size)

Using latest fxmaster and foundry 8.9, but also observed on foundry 8.8.

When the fog disappears, I have to fiddle with a fog setting and then hit save to get it to reappear.

**Comment by ghost91-** [comment]
In GitLab by @Uniwars68 on Aug 30, 2021, 11:39

is fxmaster still developped ?

**Comment by ghost91-** [comment]
In GitLab by @gray.geistag on Sep 27, 2021, 20:17

@BlackMoons I am getting the same issues as you did above with the "rrggbb" error. Did you ever find a fix? I have some scenes where the effects work, but one scene in particular where it does not. 

![image](/uploads/a5f13ce69f74eee458612a65b547ae53/image.png)

I am also seeing this...

![image](/uploads/dfcbbec1d11c1576b08f5fc3d2377192/image.png)

**Comment by ghost91-** [comment]
In GitLab by @BlackMoons on Nov 11, 2021, 02:04

Nope.. other then just cranking the density wayyyy down makes it happen a little less.

**Comment by ghost91-** [comment]
The issue with `TypeError: Cannot read property 'callback' of undefined` is most likely related to #91. See https://github.com/ghost-fvtt/fxmaster/issues/91#issuecomment-991818457 and the updated readme for a resolution.

Regarding clouds / fog disappearing: I am having trouble with reproducing that, same for the "rrggbb" warnings.
@cs96and, @BlackMoons, @ravingdragoon, @SirGawain is this still happening for you? If yes, could you help me out by specifying in more detail how to reproduce it? In particular, which version of foundryvtt are you using, which version of FXMaster, which effects are you creating (with which parameters) and how are you creating them (via the scene controls, via a macro, via a different module, etc.)?

**Comment by BlackMoons** [comment]
@ghost91- Please stop mentioning me on every single post, its flooding my inbox.

**Comment by ghost91-** [comment]
This was done automatically by the tool that converted the issues from GitLab to here, sorry for the inconvenience. Just the last one was actually created by me. I'm just trying to solve the problems you apparently were having with this module. If you don't have them anymore or don't care anymore, that's fine, just let me know. Just trying to get a hold of which of these issues are actually still valid.

**Comment by ravingdragoon** [comment]
I am still getting the error, but not as frequently. Also, since libwrapper has updated to show conflicts, the error denotes that Perfect Vision is involved in the problem.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'callback')
[Detected 3 packages: fxmaster, perfect-vision, lib-wrapper]
    at WeatherLayer.js:160
    at Array.forEach (<anonymous>)
    at WeatherLayer.configureEffect (WeatherLayer.js:158)
    at WeatherLayer.drawWeather (WeatherLayer.js:150)
    at Z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:502)
    at WeatherLayer.wrapper (patch.js:17)
    at WeatherLayer.🎁Canvas.layers.fxmaster.prototype.drawWeather#0 (libWrapper-wrapper.js:182)
    at fxmaster.js:84
    at Function._call (eval at <anonymous> (libWrapper-errors.js:8), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at Canvas.draw (foundry.js:17698)
    at async Canvas.<anonymous> (canvas.js:39)
    at async Scene.view (foundry.js:15619)
```

**Comment by ghost91-** [comment]
I am pretty sure this problem (Cannot read properties of undefined (reading 'callback')) is related to #91. Maybe one of those other modules is invoking FXMaster incorrectly. I'll also adjust things to be a bit more robust here, so that invalid parameters are just ignored (and print a warning) instead of resulting in an error.

**Comment by BlackMoons** [comment]
> This was done automatically by the tool that migrated the issues from GitLab to GitHub, sorry for the inconvenience. Just the last one was actually created by me. I'm just trying to solve the problems you apparently were having with this module. If you don't have them anymore or don't care anymore, that's fine, just let me know. Just trying to get a hold of which of these issues are actually still valid.

I stopped using the mod because of these errors/issues persisting without any fixes and the mod author having disappeared. It seemed much worse on large maps.

**Comment by ravingdragoon** [comment]
Is this updated module stable for use, or should I wait to update until you publish it?

**Comment by ghost91-** [comment]
Wait until it is published. There are still some moving parts. Shouldn’t be too long, I plan to make a release when or soon after foundry V9 is released. Basically just need to get a few minor things in order and wait for foundry support to give me access to the admin page for this module.

**Comment by ravingdragoon** [comment]
> Wait until it is published. There are still some moving parts. Shouldn’t be too long, I plan to make a release when or soon after foundry V9 is released. Basically just need to get a few minor things in order and wait for foundry support to give me access to the admin page for this module.

Sounds good.

**Comment by ravingdragoon** [comment]
I also receive the following warning occasionally, and whenever it happens I am unable to either remove or add the effect that caused the warning until I reload the page.

```
jquery.min.js:2 The specified value "undefined" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
xe	@	jquery.min.js:2
S.parseHTML	@	jquery.min.js:2
S.fn.init	@	jquery.min.js:2
S	@	jquery.min.js:2
_renderInner	@	foundry.js:2222
await in _renderInner (async)		
_renderInner	@	foundry.js:2747
_render	@	foundry.js:2055
await in _render (async)		
🎁call_wrapped	@	libWrapper-wrapper.js:502
🎁Application.prototype._render#lib-wrapper	@	listeners.js:110
🎁Application.prototype._render#0	@	libWrapper-wrapper.js:182
_render	@	foundry.js:2736
render	@	foundry.js:2011
onClick	@	controls.js:29
_onClickTool	@	foundry.js:27752
🎁call_wrapped	@	libWrapper-wrapper.js:502
🎁SceneControls.prototype._onClickTool#df-architect	@	WallChangeType.ts:23
🎁SceneControls.prototype._onClickTool#0	@	libWrapper-wrapper.js:182
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2
```

**Comment by ghost91-** [comment]
@ravingdragoon now that the new version has been published, could you check if you still encounter any issues?

**Comment by ravingdragoon** [comment]
I spent about 10 minutes trying and I was unable to get either error to reproduce.

**Comment by ghost91-** [comment]
Thanks for testing! I'll close this issue then. Should you encounter it again, feel free to create a new issue.
