### ISSUE TITLE
pt-BR missing localization strings

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#96]
In GitLab by @MagelaCE on Nov 26, 2021, 02:44
https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/-/issues/170

lang file with brazilian portuguese localization[pt-BR.json](https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/uploads/6a43f9620d565e8e5fde8b133bc70d35/pt-BR.json)

**Comment by ghost91-** [comment]
In GitLab by @MagelaCE on Nov 26, 2021, 02:44

changed the description

**Comment by ghost91-** [comment]
Hi @MagelaCE, unfortunately I don't speak Portuguese. Is the file you attached an updated version that contains all the localizations that were missing? If so, I can add them.

**Comment by MagelaCE** [comment]
Yes, the file is a update with localizations
