### ISSUE TITLE
Filter via macro not working as first filter

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#97]
In GitLab by @Danii0206 on Dec 6, 2021, 19:00
https://gitlab.com/mesfoliesludiques/foundryvtt-fxmaster/-/issues/171

Hi,

first: thank you for this awesome module!

Now to the bugreport: I made a macro to switch the colorfilter. (Btw the example in the compendium seems outdated.)
It does work, but only if I use a filter through the left hand menu first. The macro only works as the second filter applied. Doesn't matter if the first is still active, only that there was another filter before I use the macro.

The code I use is:

`FXMASTER.filters.switch("redfilterID", "color", { color: {value: "#880000", apply: true}, gamma: 1.0, contrast: 1.0, brightness: 1.0, saturation: 1.0 });`

Am I missing something or is this indeed a bug?

Kind regards
Danii

**Comment by ghost91-** [comment]
@Danii0206 With which version of foundry and did you run into this? Can you still reproduce it?

**Comment by Danii0206** [comment]
Yes I can reproduce it on every scene I create.

Steps to reproduce:
- make new scene with background picture
- execute macro (see above post)

Expected outcome:
Scene turns red

Observed outcome:
- No change to scene
- In FXMaster Filter Controls the color filter is set to the options defined by the macro

Workaround:
- make new scene
- set any colorfilter through fxmaster filter controls
- delete colorfilter
- use macro
- > scene turns red

Foundry 0.8.9
FXMaster 1.2.1
System: Vampire the Masquerade 5e 1.7.1

**Comment by ghost91-** [comment]
I figured out what the problem was. I'll create a release with the fix as soon as possible but first maintenance of FXMaster needs to be transferred to me by foundry support.
